COLUMNS:

  encounter_id: int64

  patient_nbr: int64

  race: object

  gender: object

  age: object

  weight: object

  admission_type_id: int64

  discharge_disposition_id: int64

  admission_source_id: int64

  time_in_hospital: int64

  payer_code: object

  medical_specialty: object

  num_lab_procedures: int64

  num_procedures: int64

  num_medications: int64

  number_outpatient: int64

  number_emergency: int64

  number_inpatient: int64

  diag_1: object

  diag_2: object

  diag_3: object

  number_diagnoses: int64

  max_glu_serum: object

  A1Cresult: object

  metformin: object

  repaglinide: object

  nateglinide: object

  chlorpropamide: object

  glimepiride: object

  acetohexamide: object

  glipizide: object

  glyburide: object

  tolbutamide: object

  pioglitazone: object

  rosiglitazone: object

  acarbose: object

  miglitol: object

  troglitazone: object

  tolazamide: object

  examide: object

  citoglipton: object

  insulin: object

  glyburide-metformin: object

  glipizide-metformin: object

  glimepiride-pioglitazone: object

  metformin-rosiglitazone: object

  metformin-pioglitazone: object

  change: object

  diabetesMed: object

  readmitted: object

TARGET_COLUMN:
  name: readmitted