# Config file for ML project stages and artifact locations 

artifacts_root: artifacts # Root folder for all artifacts


# Data ingestion config
data_ingestion: 
  root_dir: artifacts/data_ingestion # Location for data ingestion artifacts
  source_URL: https://github.com/Krish-Goyani/DataSets/raw/main/diabetes+130-us+hospitals+for+years+1999-2008%20(1).zip # Raw data source
  local_data_file: artifacts/data_ingestion/data.zip # Location to save raw data
  unzip_dir: artifacts/data_ingestion # Location to unzip raw data


# Data validation config
data_validation:
  root_dir: artifacts/data_validation 
  unzip_data_dir: artifacts/data_ingestion/diabetic_data.csv # Input file for validation
  status_file: artifacts/data_validation/status.txt # Validation status output


# Data transformation config  
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/diabetic_data.csv # Input data for transformation


# Model trainer config
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv # Input training data
  test_data_path: artifacts/data_transformation/test.csv # Input test data
  model_name: model.joblib # Output model file


# Model evaluation config
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv # Test data
  model_path: artifacts/model_trainer/model.joblib # Input model
  metric_file_name: artifacts/model_evaluation/metrics.json # Output metrics